### ISSUE TITLE
Issue while doing a make on 5.2.1 release.

### ISSUE THREAD

**Issue by sseshachala** [perfwatcher/collectd-pw#1]
Issue with new release 5.2.1
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -DPREFIX=\"/usr\" -DCONFIGFILE=\"/usr/etc/collectd.conf\" -DLOCALSTATEDIR=\"/usr/var\" -DPKGLOCALSTATEDIR=\"/usr/var/lib/collectd\" -DPIDFILE=\"/usr/var/run/collectd.pid\" -DPLUGINDIR=\"/usr/lib/collectd\" -DPKGDATADIR=\"/usr/share/collectd\" -Wall -Werror -g -O2 -MT notify_file.lo -MD -MP -MF .deps/notify_file.Tpo -c notify_file.c  -fPIC -DPIC -o .libs/notify_file.o
notify_file.c: In function 'notify_file_notify':
notify_file.c:163:22: error: variable 'notify_file_fd' set but not used [-Werror=unused-but-set-variable]

**Comment by ymettier** [comment]
Hello,

In notify_file.c, remove the 2 lines containing 'notify_file_fd'. Then recompile.

Branchs plugin-notify_file/5.2.0,  plugin/notify_file, release/5.2.0 and release/5.2.1 were updated.

Note : when you specify the version number (5.2.1), don't forget the extra version number (like 20130312 for yesterday's version or like 20130313 for this morning's version with another bug fixed in notify_file.c).

Regards,
Yves

**Comment by sseshachala** [comment]
Thank you.
